exclude: ".git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.259"
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, --fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.2.0"
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--warn-unused-configs, --config-file=mypy.ini, --install-types]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
