site_name: Extech
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
