name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - "documentation/**"

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        working-directory: documentation
        run: pip install -r requirements.txt

      - name: Build documentation
        working-directory: documentation
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        working-directory: documentation
        run: |
          git worktree add gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../site/* .
          git add .
          git commit -m "MkDocs Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages
